name: Build ngx_cache_purge

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up prerequisites
      run: |
        sudo apt update
        sudo apt install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev wget

    - name: Download Nginx source
      run: |
        wget http://nginx.org/download/nginx-1.24.0.tar.gz
        tar -zxvf nginx-1.24.0.tar.gz
        mv nginx-1.24.0 nginx

    - name: Compile ngx_cache_purge as dynamic module
      run: |
        git clone https://github.com/FRiCKLE/ngx_cache_purge.git
        cd nginx
        ./configure --with-compat --add-dynamic-module=../ngx_cache_purge
        make modules

    - name: Upload ngx_cache_purge module
      uses: actions/upload-artifact@v3
      with:
        name: ngx_cache_purge_module
        path: |
          nginx/objs/ngx_http_cache_purge_module.so
